name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: pnpm/action-setup@v2
        with:
          version: 7.15.0
      - name: Deps
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Test
        run: pnpm test
